# Generated by Django 3.1.1 on 2020-09-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact_no', models.IntegerField()),
                ('present_address', models.CharField(max_length=500)),
                ('nid_no', models.CharField(max_length=200)),
            ],
        ),
    ]
