# Generated by Django 3.1.1 on 2020-09-23 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=25)),
                ('post_code', models.CharField(max_length=5)),
                ('nid_no', models.CharField(max_length=17)),
                ('phone_no', models.CharField(max_length=11)),
                ('profile_pic', models.ImageField(blank=True, upload_to='uploads/user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
